services: 
   
    temperature-collection:
        build: ./temperature_dc
        privileged: true
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        volumes:
            - ./temperature_dc/config:/app/config

        networks:
            internal:
                aliases:
                    - temperature-dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-temperature-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
